# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'AplicationTest' do
  pod 'AFNetworking', '~> 3.0'
  pod 'Haneke', '~> 1.0'
  pod 'DZNEmptyDataSet'
end

target 'AplicationTestTests' do

end

